### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by Lk991** [KasperiP/kiderat-desktop#15]
I just tested the bot about an hour ago, it worked then. Now I tried it again just to be safe since theres a ticket release coming for a big event tomorrow, and now it doesnt work anymore, mabye kide changed something again in their API? 
![Skärmbild 2023-11-07 214459](https://github.com/KasperiP/kiderat-desktop/assets/132063971/f694b364-746b-4c60-b9b1-bb2a7066b48a)

**Comment by KasperiP** [comment]
Kide has made some API changes once again, even outside office hours. I hope their developers are well-compensated 😵‍💫. These changes are addressed in the latest update, which I will publish as soon as the build pipeline finishes.
