### ISSUE TITLE
kide did a patch so now the bot doesnt work anymore

### ISSUE THREAD

**Issue by cheekyboiii** [KasperiP/kiderat-desktop#16]
will you be able to do a fix before 12pm tomorrow?

**Comment by KasperiP** [comment]
Yeah I will check this ASAP

**Comment by KasperiP** [comment]
Kide has made some API changes once again, even outside office hours. I hope their developers are well-compensated 😵‍💫. These changes are addressed in the latest update, which I will publish as soon as the build pipeline finishes.
