### ISSUE TITLE
Eettistä bottaamista

### ISSUE THREAD

**Issue by kimtakala** [KasperiP/kiderat-desktop#8]
Lisää vapaa valintainen yläraja varattujen lippujen määrälle. (esim. 2 per kategoria)

**Comment by KasperiP** [comment]
Kaunis idea, mutta en nää tätä tarpeelliseksi. Kiderat operoi sen yhden käyttäjän puitteissa ja jos tapahtumajärjestäjä on laittanut todella korkeat limitit per käyttäjä, niin korjatkoot omat myyntinsä. Mitään monen käyttäjän tukea ei kuitenkaan ole koskaan tähän projektiin tulossa, joka oikein kunnon trokariboteista löytyy ja jolla käyttäjäkohtaisia lippurajoituksia pyritään kiertämään.

**Comment by kimtakala** [comment]
En ollut tietonen tosta tapahtuman järjestäjän limiitistä. Siinä tapauksessa samaa mieltä 👍🏻
